spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: none     # let Flyway manage schema

  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-disabled: false   # TEMPORARY: allow clean during fixes

  h2:
    console:
      enabled: true
      path: /h2-console
