spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/questionnaire
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: dulmin
  
  jpa:
    hibernate:
      ddl-auto: update   # don’t auto-change schema; just check it
  flyway:
    enabled: true
    baseline-on-migrate: true   # DB already has tables -> create a baseline marker
    # baseline-version: 1       # optional (default 1)
  app:
    storage:
      root: uploads


