spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/questionnaire
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: dulmin

  jpa:
    hibernate:
      ddl-auto: none         # don't let Hibernate change the schema
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 2      # <-- important: DB already matches up to V2
    schemas: public

  sql:
    init:
      mode: never            # avoid Spring SQL init interfering

app:
  storage:
    root: uploads
