-- Drop old configuration columns
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS ssim_weight;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS ssim_threshold;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS mse_weight;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS mse_threshold;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS histogram_weight;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS histogram_threshold;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS combined_threshold;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS resize_width;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS resize_height;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS blur_kernel_size;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS min_contour_area;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS dilation_iterations;
ALTER TABLE anomaly_detection_config DROP COLUMN IF EXISTS erosion_iterations;

-- Add new configuration columns with default values from Python dict
ALTER TABLE anomaly_detection_config ADD COLUMN delta_k_sigma DOUBLE PRECISION DEFAULT 0.28;
ALTER TABLE anomaly_detection_config ADD COLUMN delta_abs_min INTEGER DEFAULT 5;
ALTER TABLE anomaly_detection_config ADD COLUMN min_blob_area_px INTEGER DEFAULT 24;
ALTER TABLE anomaly_detection_config ADD COLUMN open_iters INTEGER DEFAULT 2;
ALTER TABLE anomaly_detection_config ADD COLUMN dilate_iters INTEGER DEFAULT 8;
ALTER TABLE anomaly_detection_config ADD COLUMN keep_component_min_ratio DOUBLE PRECISION DEFAULT 0.3;
ALTER TABLE anomaly_detection_config ADD COLUMN fault_red_ratio DOUBLE PRECISION DEFAULT 0.00007;
ALTER TABLE anomaly_detection_config ADD COLUMN fault_red_min_pixels INTEGER DEFAULT 5;
ALTER TABLE anomaly_detection_config ADD COLUMN potential_yellow_ratio DOUBLE PRECISION DEFAULT 0.0002;
ALTER TABLE anomaly_detection_config ADD COLUMN fullwire_hot_fraction DOUBLE PRECISION DEFAULT 0.4;
ALTER TABLE anomaly_detection_config ADD COLUMN elongated_aspect_ratio DOUBLE PRECISION DEFAULT 3.0;
ALTER TABLE anomaly_detection_config ADD COLUMN merge_close_frac DOUBLE PRECISION DEFAULT 0.06;
ALTER TABLE anomaly_detection_config ADD COLUMN min_cluster_area_px INTEGER DEFAULT 400;
ALTER TABLE anomaly_detection_config ADD COLUMN sidebar_search_frac DOUBLE PRECISION DEFAULT 0.35;
ALTER TABLE anomaly_detection_config ADD COLUMN sidebar_min_width_frac DOUBLE PRECISION DEFAULT 0.03;
ALTER TABLE anomaly_detection_config ADD COLUMN sidebar_max_width_frac DOUBLE PRECISION DEFAULT 0.09;
ALTER TABLE anomaly_detection_config ADD COLUMN sidebar_min_valid_frac DOUBLE PRECISION DEFAULT 0.6;
ALTER TABLE anomaly_detection_config ADD COLUMN sidebar_hue_span_deg INTEGER DEFAULT 25;
ALTER TABLE anomaly_detection_config ADD COLUMN sidebar_margin_px INTEGER DEFAULT 10;
ALTER TABLE anomaly_detection_config ADD COLUMN text_bottom_band_frac DOUBLE PRECISION DEFAULT 0.1;
ALTER TABLE anomaly_detection_config ADD COLUMN mask_top_left_overlay BOOLEAN DEFAULT true;
ALTER TABLE anomaly_detection_config ADD COLUMN top_left_box VARCHAR(255) DEFAULT '0.0,0.0,0.5,0.12';
ALTER TABLE anomaly_detection_config ADD COLUMN h_bins INTEGER DEFAULT 256;
ALTER TABLE anomaly_detection_config ADD COLUMN hist_distance_min DOUBLE PRECISION DEFAULT 0.03;
ALTER TABLE anomaly_detection_config ADD COLUMN red_bg_ratio_min_increase DOUBLE PRECISION DEFAULT 0.001;
ALTER TABLE anomaly_detection_config ADD COLUMN red_bg_min_abs DOUBLE PRECISION DEFAULT 0.001;
ALTER TABLE anomaly_detection_config ADD COLUMN roi_s_min INTEGER DEFAULT 25;
ALTER TABLE anomaly_detection_config ADD COLUMN roi_v_min INTEGER DEFAULT 50;
ALTER TABLE anomaly_detection_config ADD COLUMN blue_h_lo INTEGER DEFAULT 90;
ALTER TABLE anomaly_detection_config ADD COLUMN blue_h_hi INTEGER DEFAULT 128;
ALTER TABLE anomaly_detection_config ADD COLUMN blue_s_min INTEGER DEFAULT 40;
ALTER TABLE anomaly_detection_config ADD COLUMN blue_v_min INTEGER DEFAULT 40;
ALTER TABLE anomaly_detection_config ADD COLUMN black_v_hi INTEGER DEFAULT 40;
ALTER TABLE anomaly_detection_config ADD COLUMN white_bg_S_max INTEGER DEFAULT 30;
ALTER TABLE anomaly_detection_config ADD COLUMN white_bg_V_min INTEGER DEFAULT 170;
ALTER TABLE anomaly_detection_config ADD COLUMN white_bg_exclude_near_warm_px INTEGER DEFAULT 4;
ALTER TABLE anomaly_detection_config ADD COLUMN white_bg_column_frac DOUBLE PRECISION DEFAULT 0.25;
ALTER TABLE anomaly_detection_config ADD COLUMN white_bg_row_frac DOUBLE PRECISION DEFAULT 0.15;
