-- H2/Postgres-friendly create for "questions"
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text TEXT NOT NULL
    -- do NOT include created_at here; V2 adds it
);
