CREATE TABLE IF NOT EXISTS transformers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6),
    transformer_no VARCHAR(255) NOT NULL,
    pole_no VARCHAR(255) NOT NULL,
    region VARCHAR(255) NOT NULL,
    transformer_type VARCHAR(255) NOT NULL,
    CHECK (transformer_type IN ('BULK','DISTRIBUTION'))
);
