CREATE TABLE IF NOT EXISTS inspections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP(6) NOT NULL,
    inspector VARCHAR(255) NOT NULL,
    notes TEXT,
    status VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    transformer_id BIGINT NOT NULL,
    CHECK (status IN ('OPEN','IN_PROGRESS','CLOSED')),
    CONSTRAINT fk_inspections_transformer
        FOREIGN KEY (transformer_id) REFERENCES transformers(id) ON DELETE CASCADE
);
