CREATE TABLE IF NOT EXISTS transformer_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content_type VARCHAR(255),
    created_at TIMESTAMP(6),
    humidity DOUBLE,
    location_note VARCHAR(255),
    temperaturec DOUBLE,              -- matches your code/dump field name
    weather VARCHAR(255),
    filename VARCHAR(255),
    image_type VARCHAR(255) NOT NULL,
    size_bytes BIGINT,
    storage_path VARCHAR(255),
    uploader VARCHAR(255) NOT NULL,
    transformer_id BIGINT NOT NULL,
    CHECK (image_type IN ('BASELINE','MAINTENANCE')),
    CHECK (weather IN ('SUNNY','CLOUDY','RAINY')),
    CONSTRAINT fk_images_transformer
        FOREIGN KEY (transformer_id) REFERENCES transformers(id) ON DELETE CASCADE
);
